version: '3'

services: 
  todos-database:
    image: postgres:15.3
    container_name: todos-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
      